version: '3.8'

services:
  db:
    image: postgres:15
    container_name: ds_portfolio_db
    environment:
      - POSTGRES_DB=ds_portfolio
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build:
      context: ..
      dockerfile: docker/fastapi/Dockerfile
    container_name: ds_portfolio_api
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/ds_portfolio
    ports:
      - "8000:8000"

  web:
    build:
      context: ..
      dockerfile: docker/streamlit/Dockerfile
    container_name: ds_portfolio_web
    depends_on:
      - api
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://api:8000

volumes:
  postgres_data:
