name: Deploy to Cloud Run

on:
  push:
    branches:
      - main
    paths:
      - 'app/**'
      - 'requirements.txt'
      - 'Dockerfile'
  workflow_dispatch:

env:
  PROJECT_ID: retc-emissions-analysis
  SERVICE_NAME: ds-portfolio
  REGION: us-central1

jobs:
  deploy:
    name: Deploy to Cloud Run
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ env.PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true    - name: Deploy to Cloud Run
      id: deploy
      uses: google-github-actions/deploy-cloudrun@v1
      with:
        service: ${{ env.SERVICE_NAME }}
        region: ${{ env.REGION }}
        source: .
        flags: >-
          --allow-unauthenticated 
          --memory=512Mi 
          --cpu=1 
          --port=8080
          --timeout=300
          --cpu-boost
          --max-instances=5
          --min-instances=0
          --set-env-vars="FIRESTORE_COLLECTION=portfolio_feedback,GCP_PROJECT_ID=${{ env.PROJECT_ID }},GCP_LOCATION=${{ env.REGION }}"

    - name: Show Output
      run: echo ${{ steps.deploy.outputs.url }}
