[server]
# Configuración para ejecución local
maxUploadSize = 50
enableCORS = true
enableXsrfProtection = true
headless = true
port = 8501
address = "localhost"

[browser]
gatherUsageStats = false
serverAddress = "localhost"

[runner]
# Reducir la magnitud del parámetro fastReruns para disminuir el uso de memoria
fastReruns = false

[theme]
# Tema personalizado para la aplicación
primaryColor = "#6366f1"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#f8f9fa"
textColor = "#262730"
font = "sans serif"

[logger]
level = "warning"

[client]
# Optimización para contenedores y entornos cloud
showErrorDetails = false
toolbarMode = "minimal"

[caching]
# Configuración de caché para mejorar rendimiento y reducir uso de memoria
enable = true
memoryLimit = 1000
diskLimit = 2000
