[server]
# Configuración optimizada para Google Cloud Run
enableCORS = false
enableXsrfProtection = false
headless = true
port = 8080
address = "0.0.0.0"
enableHealthEndpoint = true
fileWatcherType = "none"  # Desactivar el vigilante de archivos para mejorar el rendimiento
maxUploadSize = 50

[browser]
gatherUsageStats = false
serverAddress = "0.0.0.0"
serverPort = 8080

[runner]
# Optimizaciones para reducir uso de memoria
magicEnabled = true
fastReruns = false  # Desactivado para reducir uso de memoria

[theme]
# Tema personalizado para la aplicación
primaryColor = "#6366f1"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#f8f9fa"
textColor = "#262730"
font = "sans serif"

[logger]
level = "warning"

[client]
# Optimización para contenedores y entornos cloud
showErrorDetails = false
toolbarMode = "minimal"

[caching]
# Configuración de caché para mejorar rendimiento y reducir uso de memoria
enable = true
memoryLimit = 1000
diskLimit = 2000

[global]
# Optimizaciones de memoria
dataFrameSerialization = "arrow"

[deprecation]
# Desactivar advertencias de deprecación
showfileUploaderEncoding = false
showPyplotGlobalUse = false
