[streamlit]
# Secretos para la configuración de Streamlit Cloud
environment = "cloud"

[contact]
email = "ds.portfolio.chile@gmail.com"
linkedin = "https://www.linkedin.com/in/daniel-andres-mardones-sanhueza-27b73777"
github = "https://github.com/Denniels"

[app]
# Configuración específica de la aplicación
name = "Portfolio Data Science Chile"
version = "2.0.0"
update_date = "Junio 2025"
